---
- name: Network | NW-Verifier | Installing network verification tools
  apt:
    name: "{{ nw_hc.verification.packages }}"
    state: present

- name: Network | NW-Verifier | Copying verification script
  template:
    src: 'templates/usr/local/sbin/ansibleguy.linux_networking/activate_network.py.j2'
    dest: "{{ nw_hc.network_script_dir }}/{{ nw_hc.verification.script }}"
    owner: 'root'
    group: 'root'
    mode: 0755

- name: Network | NW-Verifier | Copying verification service
  template:
    src: 'templates/etc/systemd/system/ansibleguy.linux_networking.activate_network.service.j2'
    dest: "/etc/systemd/system/{{ nw_hc.verification.service }}"
    owner: 'root'
    group: 'root'
    mode: 0644

- name: Network | NW-Verifier | Starting verification service
  systemd:
    daemon_reload: yes
    name: "{{ nw_hc.verification.service }}"
    state: started
    no_block: true
  ignore_errors: true
  async: "{{ nw.reload_timeout }}"
  poll: 2

# todo: if networking.service fails to restart it will not display an error (?); keeps old config

- name: Network | NW-Verifier | Updating ip used in this execution
  set_fact:
    ansible_host: "{{ post_apply_ip }}"
  when: nw.post_apply_ip is defined

- name: Network | NW-Verifier | Waiting to re-establish connection
  wait_for_connection:
    timeout: "{{ nw.verification.apply_timeout }}"
  register: connection_restore
  ignore_errors: true

- name: Network | NW-Verifier | Unable to connect
  fail:
    msg: 'It seems like we lost the connection to the target-host.
    This should not happen. (but might so if the ip was changed on purpose..)
    Please check the logs on the target-system!'
  when:
    - connection_restore.failed is defined
    - connection_restore.failed

- name: Network | NW-Verifier | Getting network activation logs
  command: "journalctl -u {{ nw_hc.verification.service }} --no-pager -n {{ nw_hc.verification.log_output_lines }}"
  register: network_activation
  changed_when: false

- name: Network | NW-Verifier | Here are the last logs of the network activation
  debug:
    msg: "{{ network_activation.stdout_lines[1:-2] }}"
